// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cosfmipenbtnyhbeqxeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvc2ZtaXBlbmJ0bnloYmVxeGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MzIxNTUsImV4cCI6MjA2MzIwODE1NX0.8E4dRFAKR18d6j1lzMpAY70jd6yKVaiVI23OGwxL5YQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);